### ISSUE TITLE
Fix output alerts

### ISSUE THREAD

**Issue by shruti170901** [Codextream/CGPA_ESTIMATOR#11]
On pressing the submit query button, the values have to be re-entered. Fix that. One possible way can be to add a cgpa display panel below the submit query button.

**Comment by j3rrythomas** [comment]
I wish to contribute to fix this issue.

**Comment by poojadas07** [comment]
I want to contribute to solve this issue. Can I?

**Comment by shruti170901** [comment]
This issue has been fixed. But still give it a try and send a PR

**Comment by j3rrythomas** [comment]
Yes,I had send a PR on 6th itself with the solved JS file.
