### ISSUE TITLE
Adding a web page for cgpa to percentage calculation

### ISSUE THREAD

**Issue by haripriya9647** [Codextream/CGPA_ESTIMATOR#19]
add a new page for cgpa to percentage calculation which will be linked to the main page.
@shruti170901 I would like to work on this issue

**Comment by soumyashaw** [comment]
I would like to work on this as well. Maybe we could collaborate to on this? @haripriya9647

**Comment by TusharDasMe** [comment]
I would love to work on this percentage calculation page.

**Comment by shruti170901** [comment]
Dear all, I have not opened this issue. I believe people can multiply the CGPA with 10 on their own to find their percentage. Do not open trivial issues on your own. I am closing it.
