### ISSUE TITLE
Hosting of this Project

### ISSUE THREAD

**Issue by urvashi-code1255** [Codextream/CGPA_ESTIMATOR#25]
Host this Project on github  pages so that it will be easy for the contributors to see what the project is all about.
@sriharikareddy2  @shruti170901  . I want to work on this issue. Please assign this to me.

Thanks & Regards
Urvashi Anand

**Comment by shruti170901** [comment]
I think this does not require much effort and can not be classified as a legitimate issue. I am closing it.

**Comment by urvashi-code1255** [comment]
Sure @shruti170901 Mam, Please host this project on your own to help the contributors :)

**Comment by shruti170901** [comment]
That goes with the css part unsaid
