### ISSUE TITLE
Separate the js stylesheet from index.html

### ISSUE THREAD

**Issue by shruti170901** [Codextream/CGPA_ESTIMATOR#4]
At present it is included within the html file

**Comment by LazyCoder-1506** [comment]
I want to contribute to this

**Comment by shruti170901** [comment]
Hey @LazyCoder-1506! We are glad you showed your interest in solving this issue. We are assigning this to you. Once you are done with it send us a PR. Meanwhile join our slack channel and in case of any query contact either of us.

**Comment by GunjanDhanuka** [comment]
Hey! Can I also contribute to this project?

**Comment by Droyder7** [comment]
Hello @shruti170901 I also want to contribute to solve this issue. So can I start working on it and make a PR?

**Comment by akshatjain-akj** [comment]
Hello @shruti170901 I also want to contribute to solve this issue.

**Comment by ankush-agarwal-12** [comment]
Hello I am Ankush Agarwal @shruti170901 I also want to contribute to solve this issue.

**Comment by vikhyatsingh123** [comment]
hey @shruti170901 , I just created PR in which JS code is separated from it's html code.
[https://github.com/Codextream/CGPA_ESTIMATOR/pull/30](url)

**Comment by prakarsh7695** [comment]
Hey @shruti170901 , I want to contribute to this project as well...can I?

**Comment by poojadas07** [comment]
Hey @shruti170901 , I want to contribute to this project . Can I?
https://github.com/Codextream/CGPA_ESTIMATOR/pull/31

**Comment by shashank319** [comment]
Hey @shruti170901 , I want to contribute to this issue

**Comment by sandip2224** [comment]
Hello @shruti170901, is it okay to create a **.js** directly inside the same directory or will it be better to create separate folders for the **CSS** and **JS** files under the main directory and then create the corresponding files inside them?

I'm open to either of them.

**Comment by awantika10** [comment]
Hey ! Is someone working on this issue?
