### ISSUE TITLE
Add a CSS Style sheet

### ISSUE THREAD

**Issue by sriharikareddy2** [Codextream/CGPA_ESTIMATOR#5]
Make the web page visually appealing

**Comment by LazyCoder-1506** [comment]
I want to contribute to this

**Comment by sriharikareddy2** [comment]
> I want to contribute to this
Sure! You may send pull request when you're done.

**Comment by LazyCoder-1506** [comment]
Please assign this to me

**Comment by baidi-mannan** [comment]
I want to contribute to this issue

**Comment by ANMOLKUMAR-123** [comment]
i  want contribute to this issue . it possible to contribution by two or more people on same issue?

**Comment by Nishant2907** [comment]
Hello, i am interested in contributing to this issue, kindly assign this issue to me too. You can accept the best PR available :).

**Comment by tcs-kiran** [comment]
i want to contribute to this issue

**Comment by sriharikareddy2** [comment]
Sure! All of you can submit a PR. We will have a look at all of them.

**Comment by munal0803** [comment]
Can I also contribute to this issue , please

**Comment by munal0803** [comment]
can I also contribute to this issue , please

**Comment by vishudhiman** [comment]
can I also contribute to this issue

**Comment by Debanjan12** [comment]
I am interested in contributing to this issue

**Comment by sandip2224** [comment]
I am interested in contributing to this issue as well

**Comment by Abhi-Kmr2046** [comment]
I am also interested in this issue.

**Comment by TusharDasMe** [comment]
I want to make this project cool with CSS can I work on it

**Comment by ineffable23** [comment]
I'm also interested to work on this issue

**Comment by prakarsh7695** [comment]
I am very much interested to work on this issue too!

**Comment by shashank319** [comment]
i am intrested to work on this issue

**Comment by shashank319** [comment]
plz help me to contribute on this as this is my first open source project

**Comment by SaiGokul9** [comment]
I want to contribute to thus issue

**Comment by shashank319** [comment]
Please assign me this issue so that i can submit pr

**Comment by Nishant2907** [comment]
Hi @sriharikareddy2  can I use bootstrap framework in this?

**Comment by sriharikareddy2** [comment]
@Nishant2907 sure! We would look at every pull request

**Comment by shruti170901** [comment]
All of you go ahead! We cannot assign it to more than 10 people so I am not actually assigning it to everyone. But go ahead! This issue is open to everyone

**Comment by ankush-agarwal-12** [comment]
@shruti170901 I am Ankush Agarwal and looking forward to work on this issue. Please assign me.

**Comment by shashank319** [comment]
[cgpa.zip](https://github.com/Codextream/CGPA_ESTIMATOR/files/5659735/cgpa.zip)
#5

**Comment by Debabrata-bhakat** [comment]
@shruti170901 I want to contribute to this issue.
